### ISSUE TITLE
Json encoder float support is todo

### ISSUE THREAD

**Issue by whyrusleeping** [polydawn/refmt#12]
Hi friend, present for you:

```
panic: TODO finish more jsonEncoder primitives support: unhandled token <f:1> [recovered]
        panic: TODO finish more jsonEncoder primitives support: unhandled token <f:1>

goroutine 18 [running]:
testing.tRunner.func1(0xc420098d20)
        /home/why/go/src/testing/testing.go:711 +0x2d2
panic(0x5c8320, 0xc42013a800)
        /home/why/go/src/runtime/panic.go:491 +0x283
github.com/polydawn/refmt/json.(*Encoder).flushValue(0xc42009b080, 0xc420142070)
        /home/why/gopkg/src/github.com/polydawn/refmt/json/jsonEncoder.go:189 +0x233
github.com/polydawn/refmt/json.(*Encoder).Step(0xc42009b080, 0xc420142070, 0x0, 0x0, 0x0)
        /home/why/gopkg/src/github.com/polydawn/refmt/json/jsonEncoder.go:134 +0xb59
github.com/polydawn/refmt/shared.TokenPump.Run(0x6e97a0, 0xc420105f40, 0x6e9760, 0xc42009b080, 0x0, 0xc42009b080)
        /home/why/gopkg/src/github.com/polydawn/refmt/shared/pump.go:35 +0x95
github.com/polydawn/refmt/json.(*Marshaller).Marshal(0xc4200b1de8, 0x5cb500, 0xc4200e1c50, 0xc4200636d0, 0x0)
        /home/why/gopkg/src/github.com/polydawn/refmt/json/jsonHelpers.go:54 +0x8b
github.com/polydawn/refmt/json.MarshalAtlased(0x5cb500, 0xc4200e1c50, 0xc42005c330, 0xc42005c360, 0x12, 0xffffffffffffffff, 0xc420140000, 0x0, 0x0)
        /home/why/gopkg/src/github.com/polydawn/refmt/json/jsonHelpers.go:39 +0x2b0
github.com/ipfs/go-ipld-cbor.(*Node).MarshalJSON(0xc420140000, 0x0, 0x40, 0x12, 0xffffffffffffffff, 0xc420140000)
        /home/why/gopkg/src/github.com/ipfs/go-ipld-cbor/node.go:438 +0x4f
github.com/ipfs/go-ipld-cbor.TestExamples.func1(0xc420098d20)
        /home/why/gopkg/src/github.com/ipfs/go-ipld-cbor/node_test.go:385 +0x296
testing.tRunner(0xc420098d20, 0xc42000bec0)
        /home/why/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
        /home/why/go/src/testing/testing.go:789 +0x2de
exit status 2
```

**Comment by warpfork** [comment]
I have finally bothered with this, as of #53.  :)
